### ISSUE TITLE
SQLCipher 3.4.0 is out now.

### ISSUE THREAD

**Issue by brendand** [couchbaselabs/couchbase-lite-libsqlcipher#13]
Would there be anything I'd need to change in this project or can I just overwrite the sqlcipher folder with the new 3.4.0 source code?

**Comment by brendand** [comment]
Or ultimately incorporating 3.4.0 into this build would be ideal.

**Comment by pasin** [comment]
Thanks for letting us know this. Basically we would need to update the `vendor/sqlcipher` submodule and rebuild the precompiled binaries of each platform. Unfortunately we do not have the build server setup to facilitate so we have to do the build manually.

**Comment by brendand** [comment]
I just put the 3.4.0 update into the vendor/sqlcipher folder and rebuilt and there were no ill effects. Seems to be working nicely with some nice improvements in speed.

**Comment by borrrden** [comment]
Note: We need to upgrade for CBL 2.0 because SQLite 3.9+ features are required.

**Comment by borrrden** [comment]
@brendand I just merged in 3.4.1
