### ISSUE TITLE
Windows prebuilted dll looks like havn't sqlcipher functions.

### ISSUE THREAD

**Issue by netpyoung** [couchbaselabs/couchbase-lite-libsqlcipher#16]
When i try use sqlcipher.dll, but i got not found exception on 'sqlite3_key'.

so i checked dll by [dllviewer](http://www.nirsoft.net/utils/dll_export_viewer.html)

but I can't found sqlcipher's api on this dlls;

**Comment by borrrden** [comment]
This is not included in the export.  We use it via PRAGMAs.
